/**
 * Structured Day-2 insights for PokéGit.
 * Distinguishes observed / inferred / uncertain. Never invents AI %.
 */

import { openaiChatJson } from "./openai-request.js";
import { SCORE_DISCLAIMER } from "./score.js";
import { activityAdjective, activityVibe } from "./activity.js";
import { deriveBuilderHeadline, deriveBuilderOneLiner } from "./focus.js";

function daysSince(iso) {
  if (!iso) return 9999;
  return (Date.now() - new Date(iso).getTime()) / (1000 * 60 * 60 * 24);
}

function cleanLine(s) {
  return String(s)
    .replace(/\u2014/g, ".")
    .replace(/\u2013/g, ",")
    .replace(/\s*—\s*/g, ". ")
    .replace(/\s*–\s*/g, ", ")
    .replace(/\.\s*\./g, ".")
    .trim();
}

function normalizeLabeled(items) {
  if (!Array.isArray(items)) return [];
  return items
    .map((item) => {
      if (typeof item === "string") {
        return { text: cleanLine(item), kind: "inferred" };
      }
      const kind = ["observed", "inferred", "uncertain"].includes(item?.kind)
        ? item.kind
        : "inferred";
      const text = cleanLine(item?.text || item?.body || "");
      const evidence = (item?.evidence || []).filter(Boolean).map(cleanLine).slice(0, 4);
      return text ? { text, kind, evidence } : null;
    })
    .filter(Boolean)
    .slice(0, 5);
}

function pack(partial, source, extra = {}) {
  const strengths = normalizeLabeled(partial.strengths || partial.greens || []);
  const concerns = normalizeLabeled(partial.concerns || partial.reds || []);
  const interesting = normalizeLabeled(partial.interesting || []);
  const style = cleanLine(partial.style || "");
  const glanceHeadline = cleanLine(partial.glanceHeadline || "");
  const oneLiner = cleanLine(partial.oneLiner || "");
  const ai = normalizeAi(partial.aiAssistance);

  return {
    style,
    glanceHeadline,
    oneLiner,
    strengths,
    interesting,
    concerns,
    aiAssistance: ai,
    greens: strengths.map((s) => s.text),
    reds: concerns.map((s) => s.text),
    text: [style, ...strengths.map((x) => `+ ${x.text}`), ...concerns.map((x) => `- ${x.text}`)]
      .filter(Boolean)
      .join("\n"),
    source,
    unavailable: Boolean(extra.unavailable),
    ...extra,
  };
}

function normalizeAi(raw) {
  const level = ["none", "low", "moderate", "high"].includes(raw?.level) ? raw.level : "none";
  const confidence = ["low", "medium", "high"].includes(raw?.confidence)
    ? raw.confidence
    : level === "none"
      ? "medium"
      : "low";
  const evidence = (raw?.evidence || []).filter(Boolean).map(cleanLine).slice(0, 5);
  const label =
    level === "none"
      ? "Little or no public evidence"
      : level === "low"
        ? "Low"
        : level === "moderate"
          ? "Moderate"
          : "Substantial";
  const summary =
    cleanLine(raw?.summary || "") ||
    (level === "none"
      ? "Public repository signals do not clearly indicate AI-assisted development. Public GitHub data isn't sufficient to estimate what percentage of code was AI-generated."
      : `Repository signals suggest ${level} AI-assisted development. Public GitHub data isn't sufficient to estimate what percentage of code was AI-generated.`);
  return { level, confidence, label, evidence, summary };
}

/** Heuristic AI-tooling signals from public repo metadata (never a % claim). */
export function detectAiAssistance(analyzedRepos) {
  const evidence = [];
  const patterns = [
    [/copilot/i, "Copilot-related naming or config"],
    [/cursor/i, "Cursor-related config or references"],
    [/\.cursorrules/i, "Cursor rules file"],
    [/aider/i, "Aider-related references"],
    [/continue\.dev|continuedev/i, "Continue.dev references"],
    [/chatgpt|openai|claude|anthropic/i, "LLM / AI tool mentions"],
    [/generated by|auto-?generated|do not edit/i, "Generated-code markers"],
  ];

  for (const item of analyzedRepos) {
    const hay = [
      item.repo.name,
      item.repo.description,
      ...(item.repo.topics || []),
      ...(item.signals?.rootFiles || []),
    ]
      .filter(Boolean)
      .join(" ");
    for (const [re, label] of patterns) {
      if (re.test(hay)) evidence.push(`${item.repo.name}: ${label}`);
    }
  }

  const uniq = [...new Set(evidence)].slice(0, 5);
  let level = "none";
  if (uniq.length >= 4) level = "high";
  else if (uniq.length >= 2) level = "moderate";
  else if (uniq.length === 1) level = "low";

  return normalizeAi({
    level,
    confidence: uniq.length ? "low" : "medium",
    evidence: uniq,
  });
}

function buildContext(analysis) {
  const { user, profileFocus, analyzedRepos, observations, activity, activityImpression } = analysis;
  const lines = [
    `Developer: ${user.login}`,
    user.name ? `Name: ${user.name}` : null,
    user.bio ? `Bio: ${user.bio}` : null,
    "",
    "CS focus areas 0-10:",
    ...(profileFocus?.top || []).map((f) => `  ${f.label}: ${f.score}`),
    "",
    "Recent public activity (from PushEvents, ~90d window when available):",
    activity
      ? [
          `  label: ${activity.label}`,
          `  approxCommits: ${activity.commitApprox}`,
          `  reposTouched: ${(activity.reposTouched || [])
            .slice(0, 5)
            .map((r) => `${r.name}(~${r.commits})`)
            .join(", ") || "none in events"}`,
          `  newestSamplePushDays: ${activity.newestPushDays ?? "unknown"}`,
          activityImpression?.impression ? `  impression: ${activityImpression.impression}` : null,
          activity.sampleNote ? `  note: ${activity.sampleNote}` : null,
        ]
          .filter(Boolean)
          .join("\n")
      : "  (unavailable)",
    "",
    "Precomputed observations (use as grounding, rewrite into sharper prose):",
  ].filter((x) => x !== null);

  for (const obs of observations || []) {
    lines.push(`- [${obs.kind}] ${obs.title}: ${obs.body}`);
    if (obs.evidence?.length) lines.push(`  evidence: ${obs.evidence.join("; ")}`);
  }

  lines.push("", "Repos:");
  for (const item of analyzedRepos) {
    const { repo, scores, signals, pokemon } = item;
    lines.push(
      [
        `- ${repo.name} [${pokemon.name} / "${pokemon.personality}"]`,
        `  why: ${pokemon.why}`,
        `  language: ${repo.language || "unknown"}`,
        `  stars: ${repo.stargazers}, forks: ${repo.forks}, sizeKB: ${repo.size}`,
        `  lastPush: ${repo.pushedAt?.slice(0, 10)}, daysSince: ${Math.round(daysSince(repo.pushedAt))}, archived: ${Boolean(repo.archived)}`,
        `  recentPublicCommitsApprox: ${signals.recentCommitApprox ?? signals.commitSampleCount ?? "unknown"}`,
        item.oneLiner ? `  oneLiner: ${item.oneLiner}` : null,
        `  focus: ${Object.entries(item.focusScores || {})
          .sort((a, b) => b[1] - a[1])
          .slice(0, 3)
          .map(([k, v]) => `${k} ${v}`)
          .join(", ")}`,
        repo.description ? `  description: ${repo.description.slice(0, 140)}` : "  description: (none)",
      ].join("\n")
    );
  }

  lines.push("", `AI tooling heuristic: ${JSON.stringify(analysis.aiAssistanceHeuristic || {})}`);
  return lines.join("\n");
}

export function heuristicSummary(analysis) {
  const {
    user,
    profileFocus,
    analyzedRepos,
    insufficient,
    insufficientReason,
    aiAssistanceHeuristic,
    observations = [],
    activity = null,
    activityImpression = null,
  } = analysis;
  if (insufficient) {
    return pack(
      {
        style: "",
        strengths: [],
        interesting: [],
        concerns: [
          {
            text: insufficientReason || "Not enough public information to generate a meaningful profile.",
            kind: "uncertain",
          },
        ],
        aiAssistance: { level: "none", confidence: "medium" },
      },
      "heuristic"
    );
  }

  const n = analyzedRepos.length || 1;
  const langs = [...new Set(analyzedRepos.map((a) => a.repo.language).filter(Boolean))];
  const dormant = analyzedRepos.filter((a) => a.pokemon.name === "Snorlax");
  const byStars = [...analyzedRepos].sort((a, b) => b.repo.stargazers - a.repo.stargazers);
  const top = byStars[0];
  const vibe = activityVibe(activity);

  const glanceHeadline = deriveBuilderHeadline(user, profileFocus, langs.map((name) => ({ name })), activity, {
    ...analysis.contributionPulse,
    possiblyPrivate: activityImpression?.possiblyPrivate,
  });

  const topFocus = profileFocus?.top || [];
  const style =
    topFocus.length > 0
      ? `Public work reads as ${topFocus
          .slice(0, 3)
          .map((f) => f.label.toLowerCase())
          .join(", ")}.`
      : "Public work is mixed. Hard to pin one lane from this sample alone.";

  const oneLiner =
    deriveBuilderOneLiner(profileFocus, activity, {
      ...analysis.contributionPulse,
      possiblyPrivate: activityImpression?.possiblyPrivate,
    }) ||
    observations[0]?.title ||
    "A partial silhouette from public repos.";

  const strengths = [];
  if (topFocus[0] && topFocus[0].score >= 5.5) {
    strengths.push({
      text: `Clearest builder lane: ${topFocus[0].label}${topFocus[1] ? ` with ${topFocus[1].label} nearby` : ""}.`,
      kind: "inferred",
      evidence: topFocus.slice(0, 2).map((f) => `${f.label} ${f.score}/10`),
    });
  }
  if (activity?.commitApprox >= 12) {
    const topTouch = (activity.reposTouched || []).slice(0, 2).map((r) => r.name);
    strengths.push({
      text: `Recent public activity is tangible (≈${activity.commitApprox} commits${
        topTouch.length ? ` across ${topTouch.join(", ")}` : ""
      }).`,
      kind: "observed",
      evidence: [`≈${activity.commitApprox} commits in public events`],
    });
  }
  if (top && top.repo.stargazers >= 30) {
    strengths.push({
      text: `${top.repo.name} carries real gravity (${top.repo.stargazers}★).`,
      kind: "observed",
      evidence: [`${top.repo.stargazers} stars`],
    });
  }
  if (langs[0]) {
    strengths.push({
      text: `Clear ${langs[0]} footprint in the sample.`,
      kind: "observed",
      evidence: [`Primary language: ${langs[0]}`],
    });
  }
  if (!strengths.length) {
    strengths.push({
      text: `${analyzedRepos.length} owned non-fork repos selected for a closer look.`,
      kind: "observed",
      evidence: [`Sample size ${analyzedRepos.length}`],
    });
  }

  const interesting = observations.slice(0, 3).map((o) => ({
    text: `${o.title}. ${o.body.split(". ")[0]}.`,
    kind: o.kind,
    evidence: o.evidence || [],
  }));

  const concerns = [];
  if (activityImpression?.possiblyPrivate) {
    concerns.push({
      text: "Contribution graph is busier than public repo pushes. May be building privately.",
      kind: "inferred",
      evidence: [
        activityImpression.yearCount != null ? `~${activityImpression.yearCount} year contributions` : null,
        `≈${activity.commitApprox || 0} public commits in events`,
      ].filter(Boolean),
    });
  }
  if (dormant.length >= 1) {
    concerns.push({
      text: `Some projects look dormant (${dormant
        .slice(0, 2)
        .map((a) => a.repo.name)
        .join(", ")}). That may mean finished, not failed.`,
      kind: "inferred",
      evidence: dormant.slice(0, 2).map((a) => a.repo.name),
    });
  }
  if (activity?.label === "quiet" || activity?.label === "dormant") {
    concerns.push({
      text:
        activity?.newestRepoName && activity?.newestPushDays != null
          ? `Recent public activity looks quieter (last sample push ~${activity.newestPushDays}d ago on ${activity.newestRepoName}).`
          : "Recent public activity looks quieter on the sampled repos.",
      kind: "observed",
      evidence: activityImpression?.impression ? [activityImpression.impression] : [],
    });
  }
  if (!concerns.length) {
    concerns.push({
      text: "Public sample is thin enough that caveats matter more than confidence.",
      kind: "uncertain",
      evidence: [`Only ${n} repos analyzed`],
    });
  }

  return pack(
    {
      style,
      glanceHeadline,
      oneLiner,
      strengths: strengths.slice(0, 3),
      interesting: interesting.slice(0, 3),
      concerns: concerns.slice(0, 3),
      aiAssistance: aiAssistanceHeuristic || { level: "none", confidence: "medium" },
    },
    "heuristic"
  );
}

function capitalize(s) {
  return String(s || "").replace(/^\w/, (c) => c.toUpperCase());
}

function parseModelJson(raw) {
  if (!raw) return null;
  let text = raw.trim();
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenced) text = fenced[1].trim();
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

export async function generateSummary(analysis) {
  const fallback = heuristicSummary(analysis);
  if (analysis.insufficient) return fallback;

  const context = buildContext(analysis);
  const system = `You write PokéGit profile insights from structured GitHub facts.
Product name is always PokéGit. Never invent other product names.

Return ONLY JSON:
{
  "glanceHeadline": "short archetype specific to THIS person, e.g. Active TypeScript builder shipping often",
  "oneLiner": "one vibe sentence under 14 words, mention activity or stack when useful",
  "style": "1-2 short sentences on engineering style",
  "strengths": [{"text":"...","kind":"observed|inferred|uncertain","evidence":["..."]}],
  "interesting": [{"text":"...","kind":"observed|inferred|uncertain","evidence":["..."]}],
  "concerns": [{"text":"...","kind":"observed|inferred|uncertain","evidence":["..."]}],
  "aiAssistance": {
    "level": "none|low|moderate|high",
    "confidence": "low|medium|high",
    "evidence": ["optional short evidence"],
    "summary": "cautious sentence. Never invent a percentage of AI-written code."
  }
}

Epistemic rules (critical):
- OBSERVED: directly visible in public data (tests exist, CI file present, language counts, push dates, recent public commits).
- INFERRED: reasonable interpretation (prefers X, prioritizes Y). Soften language.
- UNCERTAIN: cannot tell from public GitHub (e.g. whether AI wrote the code, private work quality).
- Prefer fewer sharp claims over many mushy ones.
- glanceHeadline MUST name their CS focus (AI/ML, infra, research, graphics, frontend, systems) and activity pace. Never write generic filler like "Public GitHub engineer".
- When recent commit estimates are present, weave them in (e.g. "≈20 recent public commits", "quieter lately").
- Name concrete repos when useful. Avoid repeated stock phrases like "Limited testing infrastructure is visible"; say which repos lack tests instead.
- When a Pokémon name is relevant, use the exact name so the UI can highlight it.
- Sound human. Short sentences. No em dashes. No corporate mush.
- Always include at least 1 green-flag strength AND at least 1 red-flag concern when the sample has enough data. Soft caveats are fine for reds (thin docs, quiet activity, sparse tests). Never say "bad engineer".
- concerns: only with evidence. Prefer a gentle, evidence-backed caveat over an empty list.
- For dormant repos, allow "may simply be finished".
- Never invent skill rankings, seniority labels, IQ, or personality diagnoses.
- Prefer "public work suggests…" over "they are…".
- aiAssistance confidence is usually "low" when any AI tooling signal exists. Never invent % AI code.
- Only claim what the data supports.`;

  try {
    const result = await openaiChatJson({
      system,
      user: `Analyze this PokéGit profile.\n\n${context}`,
      temperature: 0.55,
      maxTokens: 700,
    });
    if (result.missingKey) return { ...fallback, source: "heuristic" };
    if (!result.ok) {
      console.warn("PokéGit OpenAI error", result.status || "request failed");
      return { ...fallback, unavailable: true, source: "heuristic" };
    }

    const parsed = parseModelJson(result.content);
    if (!parsed) return { ...fallback, unavailable: true, source: "heuristic" };

    if (
      (!parsed.aiAssistance?.evidence || !parsed.aiAssistance.evidence.length) &&
      analysis.aiAssistanceHeuristic?.evidence?.length
    ) {
      parsed.aiAssistance = {
        ...analysis.aiAssistanceHeuristic,
        ...(parsed.aiAssistance || {}),
        evidence: analysis.aiAssistanceHeuristic.evidence,
        level: parsed.aiAssistance?.level || analysis.aiAssistanceHeuristic.level,
      };
    }

    if (!parsed.glanceHeadline) parsed.glanceHeadline = fallback.glanceHeadline;
    if (!parsed.oneLiner) parsed.oneLiner = fallback.oneLiner;

    const packed = pack(parsed, "openai");
    // Guarantee both green and red flags when the model omits one side
    if (!packed.strengths.length && fallback.strengths.length) {
      packed.strengths = fallback.strengths;
      packed.greens = fallback.greens;
    }
    if (!packed.concerns.length && fallback.concerns.length) {
      packed.concerns = fallback.concerns;
      packed.reds = fallback.reds;
    }
    return packed;
  } catch {
    console.warn("PokéGit OpenAI failed");
    return { ...fallback, unavailable: true, source: "heuristic" };
  }
}

export { SCORE_DISCLAIMER };
