/**
 * Structured Day-2 insights for PokéGit.
 * Distinguishes observed / inferred / uncertain. Never invents AI %.
 */

import { getOpenAIKey } from "./secrets.js";
import { SCORE_DISCLAIMER } from "./score.js";

function daysSince(iso) {
  if (!iso) return 9999;
  return (Date.now() - new Date(iso).getTime()) / (1000 * 60 * 60 * 24);
}

function cleanLine(s) {
  return String(s)
    .replace(/\u2014/g, ".")
    .replace(/\u2013/g, ",")
    .replace(/\s*—\s*/g, ". ")
    .replace(/\s*–\s*/g, ", ")
    .replace(/\.\s*\./g, ".")
    .trim();
}

function normalizeLabeled(items) {
  if (!Array.isArray(items)) return [];
  return items
    .map((item) => {
      if (typeof item === "string") {
        return { text: cleanLine(item), kind: "inferred" };
      }
      const kind = ["observed", "inferred", "uncertain"].includes(item?.kind)
        ? item.kind
        : "inferred";
      const text = cleanLine(item?.text || item?.body || "");
      const evidence = (item?.evidence || []).filter(Boolean).map(cleanLine).slice(0, 4);
      return text ? { text, kind, evidence } : null;
    })
    .filter(Boolean)
    .slice(0, 5);
}

function pack(partial, source, extra = {}) {
  const strengths = normalizeLabeled(partial.strengths || partial.greens || []);
  const concerns = normalizeLabeled(partial.concerns || partial.reds || []);
  const interesting = normalizeLabeled(partial.interesting || []);
  const style = cleanLine(partial.style || "");
  const glanceHeadline = cleanLine(partial.glanceHeadline || "");
  const oneLiner = cleanLine(partial.oneLiner || "");
  const ai = normalizeAi(partial.aiAssistance);

  return {
    style,
    glanceHeadline,
    oneLiner,
    strengths,
    interesting,
    concerns,
    aiAssistance: ai,
    greens: strengths.map((s) => s.text),
    reds: concerns.map((s) => s.text),
    text: [style, ...strengths.map((x) => `+ ${x.text}`), ...concerns.map((x) => `- ${x.text}`)]
      .filter(Boolean)
      .join("\n"),
    source,
    unavailable: Boolean(extra.unavailable),
    ...extra,
  };
}

function normalizeAi(raw) {
  const level = ["none", "low", "moderate", "high"].includes(raw?.level) ? raw.level : "none";
  const confidence = ["low", "medium", "high"].includes(raw?.confidence)
    ? raw.confidence
    : level === "none"
      ? "medium"
      : "low";
  const evidence = (raw?.evidence || []).filter(Boolean).map(cleanLine).slice(0, 5);
  const label =
    level === "none"
      ? "Little or no public evidence"
      : level === "low"
        ? "Low"
        : level === "moderate"
          ? "Moderate"
          : "Substantial";
  const summary =
    cleanLine(raw?.summary || "") ||
    (level === "none"
      ? "Public repository signals do not clearly indicate AI-assisted development. Public GitHub data isn't sufficient to estimate what percentage of code was AI-generated."
      : `Repository signals suggest ${level} AI-assisted development. Public GitHub data isn't sufficient to estimate what percentage of code was AI-generated.`);
  return { level, confidence, label, evidence, summary };
}

/** Heuristic AI-tooling signals from public repo metadata (never a % claim). */
export function detectAiAssistance(analyzedRepos) {
  const evidence = [];
  const patterns = [
    [/copilot/i, "Copilot-related naming or config"],
    [/cursor/i, "Cursor-related config or references"],
    [/\.cursorrules/i, "Cursor rules file"],
    [/aider/i, "Aider-related references"],
    [/continue\.dev|continuedev/i, "Continue.dev references"],
    [/chatgpt|openai|claude|anthropic/i, "LLM / AI tool mentions"],
    [/generated by|auto-?generated|do not edit/i, "Generated-code markers"],
  ];

  for (const item of analyzedRepos) {
    const hay = [
      item.repo.name,
      item.repo.description,
      ...(item.repo.topics || []),
      ...(item.signals?.rootFiles || []),
    ]
      .filter(Boolean)
      .join(" ");
    for (const [re, label] of patterns) {
      if (re.test(hay)) evidence.push(`${item.repo.name}: ${label}`);
    }
  }

  const uniq = [...new Set(evidence)].slice(0, 5);
  let level = "none";
  if (uniq.length >= 4) level = "high";
  else if (uniq.length >= 2) level = "moderate";
  else if (uniq.length === 1) level = "low";

  return normalizeAi({
    level,
    confidence: uniq.length ? "low" : "medium",
    evidence: uniq,
  });
}

function buildContext(analysis) {
  const { user, profileScores, analyzedRepos, observations } = analysis;
  const lines = [
    `Developer: ${user.login}`,
    user.name ? `Name: ${user.name}` : null,
    user.bio ? `Bio: ${user.bio}` : null,
    "",
    "Scores 0-10:",
    `Architecture: ${profileScores.architecture}`,
    `Testing: ${profileScores.testing}`,
    `Maintenance: ${profileScores.maintenance}`,
    `Documentation: ${profileScores.documentation}`,
    `Complexity: ${profileScores.complexity}`,
    `Activity: ${profileScores.activity}`,
    "",
    "Precomputed observations (use as grounding, rewrite into sharper prose):",
  ].filter((x) => x !== null);

  for (const obs of observations || []) {
    lines.push(`- [${obs.kind}] ${obs.title}: ${obs.body}`);
    if (obs.evidence?.length) lines.push(`  evidence: ${obs.evidence.join("; ")}`);
  }

  lines.push("", "Repos:");
  for (const item of analyzedRepos) {
    const { repo, scores, signals, pokemon } = item;
    lines.push(
      [
        `- ${repo.name} [${pokemon.name} / "${pokemon.personality}"]`,
        `  why: ${pokemon.why}`,
        `  language: ${repo.language || "unknown"}`,
        `  stars: ${repo.stargazers}, forks: ${repo.forks}, sizeKB: ${repo.size}`,
        `  lastPush: ${repo.pushedAt?.slice(0, 10)}, daysSince: ${Math.round(daysSince(repo.pushedAt))}, archived: ${Boolean(repo.archived)}`,
        `  tests: ${signals.hasTests}, ci: ${signals.hasCi}, readme: ${signals.hasReadme}, docs: ${signals.hasDocs}`,
        `  scores: A${scores.architecture} T${scores.testing} M${scores.maintenance} D${scores.documentation} C${scores.complexity} Act${scores.activity}`,
        repo.description ? `  description: ${repo.description.slice(0, 140)}` : "  description: (none)",
      ].join("\n")
    );
  }

  lines.push("", `AI tooling heuristic: ${JSON.stringify(analysis.aiAssistanceHeuristic || {})}`);
  return lines.join("\n");
}

export function heuristicSummary(analysis) {
  const {
    profileScores,
    analyzedRepos,
    insufficient,
    insufficientReason,
    aiAssistanceHeuristic,
    observations = [],
  } = analysis;
  if (insufficient) {
    return pack(
      {
        style: "",
        strengths: [],
        interesting: [],
        concerns: [
          {
            text: insufficientReason || "Not enough public information to generate a meaningful profile.",
            kind: "uncertain",
          },
        ],
        aiAssistance: { level: "none", confidence: "medium" },
      },
      "heuristic"
    );
  }

  const n = analyzedRepos.length || 1;
  const langs = [...new Set(analyzedRepos.map((a) => a.repo.language).filter(Boolean))];
  const withTests = analyzedRepos.filter((a) => a.signals?.hasTests);
  const noTests = analyzedRepos.filter((a) => !a.signals?.hasTests);
  const dormant = analyzedRepos.filter((a) => a.pokemon.name === "Snorlax");
  const byStars = [...analyzedRepos].sort((a, b) => b.repo.stargazers - a.repo.stargazers);
  const top = byStars[0];

  const styleBits = [];
  if (profileScores.testing >= 7.5) styleBits.push("test-oriented");
  if (profileScores.maintenance >= 7.5) styleBits.push("highly iterative");
  if (profileScores.complexity >= 7.5) styleBits.push("complexity-comfortable");
  if (langs.length && langs.length <= 2) styleBits.push(`rooted in ${langs.join(" / ")}`);
  else if (langs.length > 3) styleBits.push("polyglot across the public sample");

  const glanceHeadline =
    styleBits.length > 0
      ? styleBits.slice(0, 2).join(", ").replace(/^\w/, (c) => c.toUpperCase()) + " engineer"
      : "Public GitHub engineer";

  const style =
    styleBits.length > 0
      ? `Public work reads as ${styleBits.slice(0, 3).join(", ")}.`
      : "Public work is mixed. Hard to pin one house style from this sample alone.";

  const oneLiner =
    observations[0]?.title ||
    (styleBits.length
      ? `Consistent, ${styleBits[0]}${styleBits[1] ? ` and ${styleBits[1]}` : ""}.`
      : "A partial silhouette from public repos.");

  const strengths = [];
  if (top && top.repo.stargazers >= 30) {
    strengths.push({
      text: `${top.repo.name} carries real gravity (${top.repo.stargazers}★).`,
      kind: "observed",
      evidence: [`${top.repo.stargazers} stars`],
    });
  }
  if (withTests.length / n >= 0.4) {
    strengths.push({
      text: `Testing shows up in ${withTests.length}/${n} analyzed repos.`,
      kind: "observed",
      evidence: withTests.slice(0, 3).map((a) => a.repo.name),
    });
  }
  if (profileScores.maintenance >= 6.5) {
    strengths.push({
      text: `Maintenance stays warm (activity ${profileScores.activity}/10).`,
      kind: "inferred",
      evidence: [`Maintenance ${profileScores.maintenance}/10`],
    });
  }
  if (profileScores.architecture >= 7) {
    strengths.push({
      text: `Structure signals look intentional (architecture ${profileScores.architecture}/10).`,
      kind: "inferred",
      evidence: [`Architecture ${profileScores.architecture}/10`],
    });
  }
  if (langs[0]) {
    strengths.push({
      text: `Clear ${langs[0]} footprint in the sample.`,
      kind: "observed",
      evidence: [`Primary language: ${langs[0]}`],
    });
  }
  if (!strengths.length) {
    strengths.push({
      text: `${analyzedRepos.length} owned non-fork repos selected for a closer look.`,
      kind: "observed",
      evidence: [`Sample size ${analyzedRepos.length}`],
    });
  }

  const interesting = observations.slice(0, 3).map((o) => ({
    text: `${o.title}. ${o.body.split(". ")[0]}.`,
    kind: o.kind,
    evidence: o.evidence || [],
  }));

  const concerns = [];
  if (noTests.length / n >= 0.4) {
    concerns.push({
      text: `Limited testing infrastructure is visible (${noTests
        .slice(0, 2)
        .map((a) => a.repo.name)
        .join(", ")}).`,
      kind: "observed",
      evidence: noTests.slice(0, 2).map((a) => `No tests in ${a.repo.name}`),
    });
  }
  if (profileScores.documentation <= 6.5) {
    concerns.push({
      text: "Documentation is thinner than the rest of the profile.",
      kind: "observed",
      evidence: [`Docs score ${profileScores.documentation}/10`],
    });
  }
  if (dormant.length >= 1) {
    concerns.push({
      text: `Some projects look dormant (${dormant
        .slice(0, 2)
        .map((a) => a.repo.name)
        .join(", ")}). That may mean finished, not failed.`,
      kind: "inferred",
      evidence: dormant.slice(0, 2).map((a) => a.repo.name),
    });
  }
  if ((profileScores.activity || 0) <= 5) {
    concerns.push({
      text: `Recent public activity looks quieter (activity ${profileScores.activity}/10).`,
      kind: "observed",
      evidence: [`Activity ${profileScores.activity}/10`],
    });
  }
  if (!concerns.length) {
    const weakest = [
      ["documentation", profileScores.documentation],
      ["testing", profileScores.testing],
      ["maintenance", profileScores.maintenance],
    ]
      .filter(([, v]) => v != null)
      .sort((a, b) => a[1] - b[1])[0];
    if (weakest) {
      concerns.push({
        text: `${weakest[0][0].toUpperCase()}${weakest[0].slice(1)} is the softer public signal (${weakest[1]}/10). Worth a closer look, not a verdict.`,
        kind: "inferred",
        evidence: [`${weakest[0]} ${weakest[1]}/10`],
      });
    } else {
      concerns.push({
        text: "Public sample is thin enough that caveats matter more than confidence.",
        kind: "uncertain",
        evidence: [`Only ${n} repos analyzed`],
      });
    }
  }

  return pack(
    {
      style,
      glanceHeadline,
      oneLiner,
      strengths: strengths.slice(0, 3),
      interesting: interesting.slice(0, 3),
      concerns: concerns.slice(0, 3),
      aiAssistance: aiAssistanceHeuristic || { level: "none", confidence: "medium" },
    },
    "heuristic"
  );
}

function parseModelJson(raw) {
  if (!raw) return null;
  let text = raw.trim();
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenced) text = fenced[1].trim();
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

export async function generateSummary(analysis) {
  const fallback = heuristicSummary(analysis);
  if (analysis.insufficient) return fallback;

  const openaiApiKey = await getOpenAIKey();
  if (!openaiApiKey) {
    return { ...fallback, source: "heuristic" };
  }

  const context = buildContext(analysis);
  const system = `You write PokéGit profile insights from structured GitHub facts.
Product name is always PokéGit. Never invent other product names.

Return ONLY JSON:
{
  "glanceHeadline": "short archetype, e.g. Product-minded full-stack engineer",
  "oneLiner": "one quoted vibe sentence, under 12 words",
  "style": "1-2 short sentences on engineering style",
  "strengths": [{"text":"...","kind":"observed|inferred|uncertain","evidence":["..."]}],
  "interesting": [{"text":"...","kind":"observed|inferred|uncertain","evidence":["..."]}],
  "concerns": [{"text":"...","kind":"observed|inferred|uncertain","evidence":["..."]}],
  "aiAssistance": {
    "level": "none|low|moderate|high",
    "confidence": "low|medium|high",
    "evidence": ["optional short evidence"],
    "summary": "cautious sentence. Never invent a percentage of AI-written code."
  }
}

Epistemic rules (critical):
- OBSERVED: directly visible in public data (tests exist, CI file present, language counts, push dates).
- INFERRED: reasonable interpretation (prefers X, prioritizes Y). Soften language.
- UNCERTAIN: cannot tell from public GitHub (e.g. whether AI wrote the code, private work quality).
- Prefer fewer sharp claims over many mushy ones.
- When a Pokémon name is relevant, use the exact name so the UI can highlight it.
- Sound human. Short sentences. No em dashes. No corporate mush.
- Name concrete repos when useful.
- Always include at least 1 green-flag strength AND at least 1 red-flag concern when the sample has enough data. Soft caveats are fine for reds (thin docs, quiet activity, sparse tests). Never say "bad engineer".
- concerns: only with evidence. Prefer a gentle, evidence-backed caveat over an empty list.
- For dormant repos, allow "may simply be finished".
- Never invent skill rankings, seniority labels, IQ, or personality diagnoses.
- Prefer "public work suggests…" over "they are…".
- aiAssistance confidence is usually "low" when any AI tooling signal exists. Never invent % AI code.
- Only claim what the data supports.`;

  try {
    const res = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${openaiApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        temperature: 0.55,
        max_tokens: 700,
        response_format: { type: "json_object" },
        messages: [
          { role: "system", content: system },
          { role: "user", content: `Analyze this PokéGit profile.\n\n${context}` },
        ],
      }),
    });

    if (!res.ok) {
      console.warn("PokéGit OpenAI error", res.status);
      return { ...fallback, unavailable: true, source: "heuristic" };
    }

    const data = await res.json();
    const parsed = parseModelJson(data.choices?.[0]?.message?.content);
    if (!parsed) return { ...fallback, unavailable: true, source: "heuristic" };

    if (
      (!parsed.aiAssistance?.evidence || !parsed.aiAssistance.evidence.length) &&
      analysis.aiAssistanceHeuristic?.evidence?.length
    ) {
      parsed.aiAssistance = {
        ...analysis.aiAssistanceHeuristic,
        ...(parsed.aiAssistance || {}),
        evidence: analysis.aiAssistanceHeuristic.evidence,
        level: parsed.aiAssistance?.level || analysis.aiAssistanceHeuristic.level,
      };
    }

    if (!parsed.glanceHeadline) parsed.glanceHeadline = fallback.glanceHeadline;
    if (!parsed.oneLiner) parsed.oneLiner = fallback.oneLiner;

    const packed = pack(parsed, "openai");
    // Guarantee both green and red flags when the model omits one side
    if (!packed.strengths.length && fallback.strengths.length) {
      packed.strengths = fallback.strengths;
      packed.greens = fallback.greens;
    }
    if (!packed.concerns.length && fallback.concerns.length) {
      packed.concerns = fallback.concerns;
      packed.reds = fallback.reds;
    }
    return packed;
  } catch (err) {
    console.warn("PokéGit OpenAI failed", err?.message || "error");
    return { ...fallback, unavailable: true, source: "heuristic" };
  }
}

export { SCORE_DISCLAIMER };
