/**
 * Structured Day-1 insights + cautious AI-assistance section.
 */

import { getOpenAIKey } from "./secrets.js";
import { SCORE_DISCLAIMER } from "./score.js";

function daysSince(iso) {
  if (!iso) return 9999;
  return (Date.now() - new Date(iso).getTime()) / (1000 * 60 * 60 * 24);
}

function cleanLine(s) {
  return String(s)
    .replace(/\u2014/g, ".")
    .replace(/\u2013/g, ",")
    .replace(/\s*—\s*/g, ". ")
    .replace(/\s*–\s*/g, ", ")
    .replace(/\.\s*\./g, ".")
    .trim();
}

function pack(partial, source, extra = {}) {
  const strengths = (partial.strengths || partial.greens || []).filter(Boolean).map(cleanLine).slice(0, 5);
  const concerns = (partial.concerns || partial.reds || []).filter(Boolean).map(cleanLine).slice(0, 5);
  const interesting = (partial.interesting || []).filter(Boolean).map(cleanLine).slice(0, 5);
  const style = cleanLine(partial.style || "");
  const ai = normalizeAi(partial.aiAssistance);

  return {
    style,
    strengths,
    interesting,
    concerns,
    aiAssistance: ai,
    // back-compat for older UI bits
    greens: strengths,
    reds: concerns,
    text: [style, ...strengths.map((x) => `+ ${x}`), ...concerns.map((x) => `- ${x}`)].filter(Boolean).join("\n"),
    source,
    unavailable: Boolean(extra.unavailable),
    ...extra,
  };
}

function normalizeAi(raw) {
  const level = ["none", "low", "moderate", "high"].includes(raw?.level) ? raw.level : "none";
  const evidence = (raw?.evidence || []).filter(Boolean).map(cleanLine).slice(0, 5);
  const label =
    level === "none"
      ? "Little or no public evidence"
      : level === "low"
        ? "Low evidence"
        : level === "moderate"
          ? "Moderate evidence"
          : "Substantial evidence";
  const summary =
    cleanLine(raw?.summary || "") ||
    (level === "none"
      ? "Public repository signals do not clearly indicate AI-assisted development."
      : `Public repository signals suggest ${level} AI-assisted development, but GitHub data cannot reliably determine what percentage of the code was AI-generated.`);
  return { level, label, evidence, summary };
}

/** Heuristic AI-tooling signals from public repo metadata (never a % claim). */
export function detectAiAssistance(analyzedRepos) {
  const evidence = [];
  const patterns = [
    [/copilot/i, "Copilot-related naming or config"],
    [/cursor/i, "Cursor-related config or references"],
    [/\.cursorrules/i, "Cursor rules file"],
    [/aider/i, "Aider-related references"],
    [/continue\.dev|continuedev/i, "Continue.dev references"],
    [/chatgpt|openai|claude|anthropic|llm/i, "LLM / AI tool mentions"],
    [/generated by|auto-?generated|do not edit/i, "Generated-code markers"],
  ];

  for (const item of analyzedRepos) {
    const hay = [
      item.repo.name,
      item.repo.description,
      ...(item.repo.topics || []),
      ...(item.signals?.rootFiles || []),
    ]
      .filter(Boolean)
      .join(" ");
    for (const [re, label] of patterns) {
      if (re.test(hay)) evidence.push(`${item.repo.name}: ${label}`);
    }
  }

  const uniq = [...new Set(evidence)].slice(0, 5);
  let level = "none";
  if (uniq.length >= 4) level = "high";
  else if (uniq.length >= 2) level = "moderate";
  else if (uniq.length === 1) level = "low";

  return normalizeAi({ level, evidence: uniq });
}

function buildContext(analysis) {
  const { user, profileScores, analyzedRepos } = analysis;
  const lines = [
    `Developer: ${user.login}`,
    user.name ? `Name: ${user.name}` : null,
    user.bio ? `Bio: ${user.bio}` : null,
    "",
    "Scores 0-10:",
    `Architecture: ${profileScores.architecture}`,
    `Testing: ${profileScores.testing}`,
    `Maintenance: ${profileScores.maintenance}`,
    `Documentation: ${profileScores.documentation}`,
    `Complexity: ${profileScores.complexity}`,
    `Activity: ${profileScores.activity}`,
    "",
    "Repos:",
  ].filter((x) => x !== null);

  for (const item of analyzedRepos) {
    const { repo, scores, signals, pokemon } = item;
    lines.push(
      [
        `- ${repo.name} [${pokemon.name}]`,
        `  language: ${repo.language || "unknown"}`,
        `  stars: ${repo.stargazers}, forks: ${repo.forks}, sizeKB: ${repo.size}`,
        `  lastPush: ${repo.pushedAt?.slice(0, 10)}, daysSince: ${Math.round(daysSince(repo.pushedAt))}, archived: ${Boolean(repo.archived)}`,
        `  tests: ${signals.hasTests}, ci: ${signals.hasCi}, readme: ${signals.hasReadme}, docs: ${signals.hasDocs}`,
        `  scores: A${scores.architecture} T${scores.testing} M${scores.maintenance} D${scores.documentation} C${scores.complexity} Act${scores.activity}`,
        repo.description ? `  description: ${repo.description.slice(0, 140)}` : "  description: (none)",
      ].join("\n")
    );
  }

  lines.push("", `AI tooling heuristic evidence: ${JSON.stringify(analysis.aiAssistanceHeuristic || {})}`);
  return lines.join("\n");
}

export function heuristicSummary(analysis) {
  const { profileScores, analyzedRepos, insufficient, insufficientReason, aiAssistanceHeuristic } = analysis;
  if (insufficient) {
    return pack(
      {
        style: "",
        strengths: [],
        interesting: [],
        concerns: [insufficientReason || "Not enough public information to generate a meaningful profile."],
        aiAssistance: { level: "none" },
      },
      "heuristic"
    );
  }

  const n = analyzedRepos.length || 1;
  const langs = [...new Set(analyzedRepos.map((a) => a.repo.language).filter(Boolean))];
  const withTests = analyzedRepos.filter((a) => a.signals?.hasTests);
  const noTests = analyzedRepos.filter((a) => !a.signals?.hasTests);
  const dormant = analyzedRepos.filter((a) => a.pokemon.name === "Snorlax");
  const byStars = [...analyzedRepos].sort((a, b) => b.repo.stargazers - a.repo.stargazers);
  const top = byStars[0];

  const styleBits = [];
  if (profileScores.testing >= 7.5) styleBits.push("test-oriented");
  if (profileScores.maintenance >= 7.5) styleBits.push("maintenance-heavy");
  if (profileScores.complexity >= 7.5) styleBits.push("comfortable with complexity");
  if (langs.length && langs.length <= 2) styleBits.push(`focused on ${langs.join(" / ")}`);
  else if (langs.length > 3) styleBits.push("polyglot across the public sample");
  const style =
    styleBits.length > 0
      ? `Public work reads as ${styleBits.slice(0, 3).join(", ")}.`
      : "Public work is mixed. Hard to pin one house style from this sample alone.";

  const strengths = [];
  if (top && top.repo.stargazers >= 30) {
    strengths.push(`${top.repo.name} carries real gravity (${top.repo.stargazers}★).`);
  }
  if (withTests.length / n >= 0.5) {
    strengths.push(`Testing shows up in ${withTests.length}/${n} analyzed repos.`);
  }
  if (profileScores.maintenance >= 7) {
    strengths.push(`Maintenance stays warm. Activity score ${profileScores.activity}/10.`);
  }
  if (profileScores.architecture >= 7) {
    strengths.push(`Repo structure signals look intentional (architecture ${profileScores.architecture}/10).`);
  }
  if (strengths.length < 3 && langs[0]) {
    strengths.push(`Clear ${langs[0]} footprint in the sample.`);
  }
  if (strengths.length < 3) {
    strengths.push(`${analyzedRepos.length} owned repos selected for a closer look.`);
  }

  const interesting = [];
  const pokes = {};
  for (const a of analyzedRepos) pokes[a.pokemon.name] = (pokes[a.pokemon.name] || 0) + 1;
  const topPoke = Object.entries(pokes).sort((a, b) => b[1] - a[1])[0];
  if (topPoke) interesting.push(`Party leans ${topPoke[0]} (${topPoke[1]} repos).`);
  if (langs.length) interesting.push(`Languages in play: ${langs.slice(0, 4).join(", ")}.`);
  const freshest = [...analyzedRepos].sort((a, b) => daysSince(a.repo.pushedAt) - daysSince(b.repo.pushedAt))[0];
  if (freshest) {
    interesting.push(
      `Most recent push in sample: ${freshest.repo.name} (~${Math.round(daysSince(freshest.repo.pushedAt))}d ago).`
    );
  }

  const concerns = [];
  if (noTests.length / n >= 0.6) {
    concerns.push(
      `Limited testing infrastructure is visible in several repos (${noTests
        .slice(0, 2)
        .map((a) => a.repo.name)
        .join(", ")}).`
    );
  }
  if (profileScores.documentation <= 5) {
    concerns.push("Documentation is thinner than the rest of the profile.");
  }
  if (dormant.length >= Math.ceil(n / 2)) {
    concerns.push(
      `Several projects look dormant (${dormant
        .slice(0, 2)
        .map((a) => a.repo.name)
        .join(", ")}). That may mean finished, not failed.`
    );
  }

  return pack(
    {
      style,
      strengths: strengths.slice(0, 3),
      interesting: interesting.slice(0, 3),
      concerns: concerns.slice(0, 3),
      aiAssistance: aiAssistanceHeuristic || { level: "none" },
    },
    "heuristic"
  );
}

function parseModelJson(raw) {
  if (!raw) return null;
  let text = raw.trim();
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenced) text = fenced[1].trim();
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

export async function generateSummary(analysis) {
  const fallback = heuristicSummary(analysis);
  if (analysis.insufficient) return fallback;

  const openaiApiKey = await getOpenAIKey();
  if (!openaiApiKey) {
    return { ...fallback, source: "heuristic" };
  }

  const context = buildContext(analysis);
  const system = `You write PokéGit profile insights from structured GitHub facts.
Return ONLY JSON:
{
  "style": "1-2 short sentences on engineering style",
  "strengths": ["bullet","bullet","bullet"],
  "interesting": ["bullet","bullet","bullet"],
  "concerns": ["bullet"] ,
  "aiAssistance": {
    "level": "none|low|moderate|high",
    "evidence": ["optional short evidence"],
    "summary": "one cautious sentence"
  }
}

Rules:
- When a repo's Pokémon type is relevant, use the exact Pokémon name (Pikachu, Dragonite, Alakazam, Blastoise, Blissey, Golem, Umbreon, Sylveon, Ditto, Snorlax, Eevee) so the UI can highlight it.
- Sound human. Short sentences. No em dashes. No corporate mush.
- Name concrete repos when useful.
- concerns: only with evidence. Empty array is fine. Never say "bad engineer".
- For dormant repos, allow "may simply be finished".
- aiAssistance: never invent an exact AI code percentage. Be cautious.
- Only claim what the data supports.`;

  try {
    const res = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${openaiApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        temperature: 0.65,
        max_tokens: 450,
        response_format: { type: "json_object" },
        messages: [
          { role: "system", content: system },
          { role: "user", content: `Analyze this profile.\n\n${context}` },
        ],
      }),
    });

    if (!res.ok) {
      console.warn("PokéGit OpenAI error", res.status);
      return { ...fallback, unavailable: true, source: "heuristic" };
    }

    const data = await res.json();
    const parsed = parseModelJson(data.choices?.[0]?.message?.content);
    if (!parsed) return { ...fallback, unavailable: true, source: "heuristic" };

    // Prefer heuristic AI evidence if model invents none but we found some
    if (
      (!parsed.aiAssistance?.evidence || !parsed.aiAssistance.evidence.length) &&
      analysis.aiAssistanceHeuristic?.evidence?.length
    ) {
      parsed.aiAssistance = analysis.aiAssistanceHeuristic;
    }

    return pack(parsed, "openai");
  } catch (err) {
    console.warn("PokéGit OpenAI failed", err?.message || "error");
    return { ...fallback, unavailable: true, source: "heuristic" };
  }
}

export { SCORE_DISCLAIMER };
